### ISSUE TITLE
502 Bad Gateway after reboot

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#16]
Hi, 
i uploaded some videos, and reboot the server, 
but peertube is unreachable, error 502 : Bad Gateway

```
root@krashboyz:/home/admin# more /var/www/peertube/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node_n/bin/node', '/opt/node_n/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart peertube@1.0.0-beta.3
6 info start peertube@1.0.0-beta.3
7 verbose unsafe-perm in lifecycle true
8 info peertube@1.0.0-beta.3 Failed to exec start script
9 verbose stack Error: peertube@1.0.0-beta.3 start: `node dist/server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/node_n/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/node_n/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid peertube@1.0.0-beta.3
11 verbose cwd /var/www/peertube
12 error Linux 3.16.0-5-amd64
13 error argv "/opt/node_n/bin/node" "/opt/node_n/bin/npm" "start"
14 error node v4.9.1
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error peertube@1.0.0-beta.3 start: `node dist/server`
17 error Exit status 1
18 error Failed at the peertube@1.0.0-beta.3 start script 'node dist/server'.
18 error This is most likely a problem with the peertube package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node dist/server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs peertube
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls peertube
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
```
root@krashboyz:/var/www/peertube# service peertube status
● peertube.service - PeerTube daemon
   Loaded: loaded (/etc/systemd/system/peertube.service; enabled)
   Active: failed (Result: start-limit) since sam. 2018-04-07 12:36:35 CEST; 7s ago
  Process: 22941 ExecStart=/bin/sh -c PATH=/opt/node_n/bin:$PATH exec npm start (code=exited, status=1/FAILURE)
 Main PID: 22941 (code=exited, status=1/FAILURE)

avril 07 12:36:35 krashboyz systemd[1]: Unit peertube.service entered failed state.
avril 07 12:36:35 krashboyz systemd[1]: peertube.service holdoff time over, scheduling restart.
avril 07 12:36:35 krashboyz systemd[1]: Stopping PeerTube daemon...
avril 07 12:36:35 krashboyz systemd[1]: Starting PeerTube daemon...
avril 07 12:36:35 krashboyz systemd[1]: peertube.service start request repeated too quickly, refusing to start.
avril 07 12:36:35 krashboyz systemd[1]: Failed to start PeerTube daemon.
avril 07 12:36:35 krashboyz systemd[1]: Unit peertube.service entered failed state.
```
i'm lost :/
restarting via service peertube stop ; service peertube start   isn't changing anything

**Comment by anmol26s** [comment]
What is 
```
node -v
npm -v
yarn -v
```

**Comment by isAAAc** [comment]
```
root@krashboyz:/var/www/peertube# node -v
v9.10.1
root@krashboyz:/var/www/peertube# npm -v
5.6.0
root@krashboyz:/var/www/peertube# yarn -v
1.5.1
```

**Comment by anmol26s** [comment]
what is the output of:
`systemctl status peertube` ?

**Comment by isAAAc** [comment]
Well, scuse me for my silence, i was busy otherelse :/
i try a new install right now to see if the trouble is still present

**Comment by anmol26s** [comment]
You can use the master branch directly now. I have merge the testing to the master.

**Comment by anmol26s** [comment]
Is the issue still resolved?

**Comment by isAAAc** [comment]
install OK, 
i reboot right now, without any video -> no error
next step is to upload some vidz && reboot again to verify is everything fine , 
i'll feed back during the evening ;)

**Comment by anmol26s** [comment]
You can be friend with other instances and check there videos on your instance too.
https://instances.joinpeertube.org/instances

**Comment by isAAAc** [comment]
ok , video uploaded and reboot done, this issue looks done ;)

(some other strange things, but i need to investigate before considering them as issues)

i think you can close for now :)

**Comment by anmol26s** [comment]
Thanks for your feedback. Don't hesitate to open new issues and help in the packaging of the app.

**Comment by filmaidykai** [comment]
● peertube.service - peertube daemon
   Loaded: loaded (/etc/systemd/system/peertube.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-01-12 06:56:24 CET; 9min ago
 Main PID: 2969 (code=exited, status=127)

Jan 12 06:56:23 tube.filmai.to systemd[1]: peertube.service: Unit entered failed state.
Jan 12 06:56:23 tube.filmai.to systemd[1]: peertube.service: Failed with result 'exit-code'.
Jan 12 06:56:24 tube.filmai.to systemd[1]: peertube.service: Service hold-off time over, scheduling restart.
Jan 12 06:56:24 tube.filmai.to systemd[1]: Stopped peertube daemon.
Jan 12 06:56:24 tube.filmai.to systemd[1]: peertube.service: Start request repeated too quickly.
Jan 12 06:56:24 tube.filmai.to systemd[1]: Failed to start peertube daemon.
Jan 12 06:56:24 tube.filmai.to systemd[1]: peertube.service: Unit entered failed state.
Jan 12 06:56:24 tube.filmai.to systemd[1]: peertube.service: Failed with result 'exit-code'.

**Comment by anmol26s** [comment]
@filmaidykai 
Do
```

$ sudo service nginx restart
$ sudo systemctl stop peertube
$ sudo systemctl start peertube
$ sudo journalctl -feu peertube

And show the output of the last command.
```

**Comment by Cam-B** [comment]
Error: Cannot find module 'lodash'

;)

**Comment by geopayme** [comment]
This error shows up on both of my instances and I had to rebuild one of them. 

` Storage / (on device /dev/vda1) has only 0.0 B (0%) space remaining (out of 47 GiB). You should really consider cleaning up some space!
 Storage /mnt/volume_ams3_01 (on device /dev/sda) still has 47 GiB (99.9%) space left (out of 47 GiB)!`

If you use a DO droplet, when you need to add a storage device DO NOT USE filesystem Ext4 as the storage choice, use EFX instead, so far my redeployed instance has no issue! 

` The system still has 387 MiB (19%) RAM available out of 2.0 GiB.
 The system has no swap at all. You should consider adding at least 512 MiB of swap to avoid situations where the system runs out of memory.
 Storage / (on device /dev/vda1) still has 27 GiB (56%) space left (out of 47 GiB)!`

On a side note, any ideas on creating the swap file? Maybe a good feature for YunoHost!

**Comment by geopayme** [comment]
Here is some thought on helping to eliminate the constant annoying error messages that are not necessary

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-9

**Comment by geopayme** [comment]
`2020-11-10 08:03:57.104 UTC [1071] [unknown]@[unknown] LOG:  incomplete startup packet
2020-11-11 13:28:38.756 UTC [929] LOG:  received fast shutdown request
2020-11-11 13:28:38.760 UTC [929] LOG:  aborting any active transactions
2020-11-11 13:28:38.769 UTC [929] LOG:  background worker "logical replication launcher" (PID 973) exited with exit code 1
2020-11-11 13:28:38.769 UTC [968] LOG:  shutting down
2020-11-11 13:28:38.794 UTC [929] LOG:  database system is shut down
2020-11-11 13:29:46.685 UTC [892] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-11-11 13:29:46.687 UTC [892] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-11-11 13:29:46.759 UTC [933] LOG:  database system was shut down at 2020-11-11 13:28:38 UTC
2020-11-11 13:29:46.799 UTC [892] LOG:  database system is ready to accept connections
2020-11-11 13:29:47.387 UTC [1046] [unknown]@[unknown] LOG:  incomplete startup packet
2020-11-13 23:27:57.085 UTC [7821] peertube__2@peertube_peertube__2 ERROR:  could not extend file "base/19185/1255": No space left on device
2020-11-13 23:27:57.085 UTC [7821] peertube__2@peertube_peertube__2 HINT:  Check free disk space.
2020-11-13 23:27:57.085 UTC [7821] peertube__2@peertube_peertube__2 STATEMENT:  CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert(OUT created boolean, OUT primary_key text)  AS $func$ BEGIN INSERT INTO "videoStreamingPlaylist" ("type","playlistUrl","p2pMediaLoaderInfohashes","p2pMediaLoaderPeerVersion","segmentsSha256Url","videoId","createdAt","updatedAt") VALUES (1,'https://political.icu/static/streaming-playlists/hls/4f77dff9-046a-457d-803a-89dfe02c9aeb/master.m3u8',ARRAY['7f95879be058bda36f1060cbb8e3a9c61dcaac0f','030111b6d5a05b2241104d7ddc0e6b341d9d2033','9fba9fda26e746baa2574d9298642379ae01321c']::VARCHAR(255)[],2,'https://political.icu/static/streaming-playlists/hls/4f77dff9-046a-457d-803a-89dfe02c9aeb/segments-sha256.json',20873,'2020-11-13 23:27:57.082 +00:00','2020-11-13 23:27:57.082 +00:00') RETURNING "id" INTO primary_key; created := true; EXCEPTION WHEN unique_violation THEN UPDATE "videoStreamingPlaylist" SET "videoId"=20873,"playlistUrl"='https://political.icu/static/streaming-playlists/hls/4f77dff9-046a-457d-803a-89dfe02c9aeb/master.m3u8',"segmentsSha256Url"='https://political.icu/static/streaming-playlists/hls/4f77dff9-046a-457d-803a-89dfe02c9aeb/segments-sha256.json',"p2pMediaLoaderInfohashes"=ARRAY['7f95879be058bda36f1060cbb8e3a9c61dcaac0f','030111b6d5a05b2241104d7ddc0e6b341d9d2033','9fba9fda26e746baa2574d9298642379ae01321c']::VARCHAR(255)[],"p2pMediaLoaderPeerVersion"=2,"type"=1,"updatedAt"='2020-11-13 23:27:57.082 +00:00' WHERE ("id" IS NULL OR ("videoId" = 20873 AND "type" = 1)) RETURNING "id" INTO primary_key; created := false; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
2020-11-14 09:37:59.098 UTC [14322] peertube__2@peertube_peertube__2 ERROR:  could not extend file "base/19185/19864": No space left on device
2020-11-14 09:37:59.098 UTC [14322] peertube__2@peertube_peertube__2 HINT:  Check free disk space.
2020-11-14 09:37:59.098 UTC [14322] peertube__2@peertube_peertube__2 STATEMENT:  UPDATE "videoImport" SET "state"=$1,"error"=$2,"updatedAt"=$3 WHERE "id" = $4
2020-11-14 09:41:09.668 UTC [943] PANIC:  could not write to file "pg_logical/replo2020-11-14 09:41:09.825 UTC [14559] LOG:  database system was not properly shut down; automatic recovery in progress
2020-11-14 09:41:09.829 UTC [14559] LOG:  redo starts at 0/57783360
2020-11-14 09:41:09.835 UTC [14559] LOG:  invalid record length at 0/5784C338: wanted 24, got 0
2020-11-14 09:41:09.835 UTC [14559] LOG:  redo done at 0/5784C2F0
2020-11-14 09:41:09.835 UTC [14559] LOG:  last completed transaction was at log time 2020-11-14 09:41:05.401885+00
2020-11-14 09:41:09.875 UTC [892] LOG:  database system is ready to accept connections
2020-11-14 09:42:34.826 UTC [14578] peertube__2@peertube_peertube__2 ERROR:  could not extend file "base/19185/19864": No space left on device
2020-11-14 09:42:34.826 UTC [14578] peertube__2@peertube_peertube__2 HINT:  Check free disk space.
2020-11-14 09:42:34.826 UTC [14578] peertube__2@peertube_peertube__2 STATEMENT:  UPDATE "videoImport" SET "state"=$1,"error"=$2,"updatedAt"=$3 WHERE "id" = $4
2020-11-14 10:21:40.089 UTC [14992] peertube__2@peertube_peertube__2 ERROR:  could not extend file "base/19185/19864": No space left on device
2020-11-14 10:21:40.089 UTC [14992] peertube__2@peertube_peertube__2 HINT:  Check free disk space.
2020-11-14 10:21:40.089 UTC [14992] peertube__2@peertube_peertube__2 STATEMENT:  UPDATE "videoImport" SET "state"=$1,"error"=$2,"updatedAt"=$3 WHERE "id" = $4
2020-11-14 10:29:16.261 UTC [15224] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:21.080 UTC [15258] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:25.786 UTC [15292] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:30.090 UTC [15326] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:34.344 UTC [15360] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:38.618 UTC [15395] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:38.620 UTC [15393] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:42.910 UTC [15428] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:47.141 UTC [15462] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:51.221 UTC [15496] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:55.355 UTC [15529] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:29:59.816 UTC [15565] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:06.425 UTC [15599] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:11.935 UTC [15634] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:11.935 UTC [15636] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:16.824 UTC [15670] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:21.605 UTC [15703] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:26.881 UTC [15736] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:31.622 UTC [15770] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:36.177 UTC [15806] peertube__2@peertube_peertube__2 LOG:  could not receive data from client: Connection reset by peer
2020-11-14 10:30:40.597 U`
