### ISSUE TITLE
YT sync no longer working

### ISSUE THREAD

**Issue by TILvids** [YunoHost-Apps/peertube_ynh#440]
Randomly about 1-2 weeks ago, YT syncs for channels stopped working on my server. I thought it might be because I was still on PeerTube 5.x.x (due to issues with Yunohost being able to upgrade to 6.x.x), so after some effort, I was finally able to get PeerTube updated to latest 6.2.1. However, after doing so, YT imports for all channels are still failing. Here is part of the error log I'm seeing:

```
error[6/21/2024, 4:29:24 PM] Cannot build import for https://www.youtube.com/watch?v=OVrF7x1utsc in channel Main ********* channel

{
  "err": {
    "stack": "Error: Command failed with exit code 1: /usr/bin/python3 /home/yunohost.app/peertube/storage/bin/yt-dlp --dump-json -f bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio/best[vcodec!*=av01][vcodec!*=vp9.2]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best https://www.youtube.com/watch?v=OVrF7x1utsc\nERROR: [youtube] OVrF7x1utsc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more\n    at makeError (file:///var/www/peertube/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (file:///var/www/peertube/node_modules/execa/index.js:124:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async YoutubeDLCLI.run (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:141:24)\n    at async YoutubeDLCLI.getInfo (file:///var/www/peertube/dist/core/helpers/youtube-dl/youtube-dl-cli.js:89:22)\n    at async YoutubeDLWrapper.getInfoForDownload
```

...it continues on like that for a while (I can get more if needed and finally concludes like so:

```
bestvideo[ext=mp4]+bestaudio[ext=m4a]/best\" \"https://www.youtube.com/watch?v=OVrF7x1utsc\"",
    "exitCode": 1,
    "stdout": "",
    "stderr": "ERROR: [youtube] OVrF7x1utsc: Sign in to confirm you’re not a bot. This helps protect our community. Learn more",
    "cwd": "/var/www/peertube",
    "failed": true,
    "timedOut": false,
    "isCanceled": false,
    "killed": false
  },
  "tags": [
    "channel-synchronization"
  ]
}
```

I definitely have users with channels that are depending on this to work, so any help is appreciated!

**Comment by TILvids** [comment]
Further update: yt-dlp community is reporting a lot of trouble lately with YT blocking access because it detects it as a "bot". My guess is that if your server gets flagged, YT sync may no longer work (no idea if that's temporary or permanent). Just another reason why creators should upload directly to PeerTube, I guess.

**Comment by tio-trom** [comment]
Yah we are seeing the same issue....nothing got fixed for you? I do not know if there is a solution for this ...  https://github.com/Chocobozzz/PeerTube/issues/6522

**Comment by TILvids** [comment]
Yup, looks like the blame all lies with Google on this one. The importance of not having a single source of content online...

**Comment by isAAAc** [comment]
i activated sync some days ago with 7 channels, 
it works for me

**Comment by tio-trom** [comment]
> i activated sync some days ago with 7 channels, it works for me

Yes but if your IP gets banned by youtube then it will not work anymore....

**Comment by JohnXLivingston** [comment]
I can confirm that youtube is blocking based on IP.
If you are self-hosting at home, it will probably continue to work.
But if you use an IP that is associated to a datacenter, the chance to be blacklisted are very high. We even saw some user have the same error message in their browser, because their internet provider use the same IP block as their servers (small associative internet provider).

Latest Peertube version includes an option to set some HTTP proxy in front of yt-dlp, so you can deport the traffic on a non-flagged IP. This is not ideal, but their is no simple technical solution to restriction imposed by youtube...
