### ISSUE TITLE
[testing] Fails to install on the reset-password step

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/peertube_ynh#5]
```
Warning: warning " > @angular/compiler-cli@5.2.6" has incorrect peer dependency "typescript@>=2.4.2 <2.7".
Warning: warning " > @ngx-meta/core@5.0.0" has unmet peer dependency "lodash@>=4.17.4".
Warning: Created symlink from /etc/systemd/system/multi-user.target.wants/peertube.service to /etc/systemd/system/peertube.service.
Warning: User unknown.
Warning: npm ERR! code ELIFECYCLE
Warning: npm ERR! errno 255
Warning: npm ERR! peertube@1.0.0-beta.1 reset-password: `node ./dist/scripts/reset-password.js "-u" "root"`
Warning: npm ERR! Exit status 255
Warning: npm ERR!
Warning: npm ERR! Failed at the peertube@1.0.0-beta.1 reset-password script.
Warning: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Warning: 
Warning: npm ERR! A complete log of this run can be found in:
Warning: npm ERR!     /root/.npm/_logs/2018-03-22T15_10_40_679Z-debug.log
Warning: !!
Warning:   peertube's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Warning: Removed symlink /etc/systemd/system/multi-user.target.wants/peertube.service.
```
The debug log says : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node_n/bin/node',
1 verbose cli   '/opt/node_n/bin/npm',
1 verbose cli   'run',
1 verbose cli   'reset-password',
1 verbose cli   '--',
1 verbose cli   '-u',
1 verbose cli   'root' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prereset-password', 'reset-password', 'postreset-password' ]
5 info lifecycle peertube@1.0.0-beta.1~prereset-password: peertube@1.0.0-beta.1
6 info lifecycle peertube@1.0.0-beta.1~reset-password: peertube@1.0.0-beta.1
7 verbose lifecycle peertube@1.0.0-beta.1~reset-password: unsafe-perm in lifecycle true
8 verbose lifecycle peertube@1.0.0-beta.1~reset-password: PATH: /opt/node_n/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/peertube/node_modules/.bin:/opt/node_n/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle peertube@1.0.0-beta.1~reset-password: CWD: /var/www/peertube
10 silly lifecycle peertube@1.0.0-beta.1~reset-password: Args: [ '-c', 'node ./dist/scripts/reset-password.js "-u" "root"' ]
11 silly lifecycle peertube@1.0.0-beta.1~reset-password: Returned: code: 255  signal: null
12 info lifecycle peertube@1.0.0-beta.1~reset-password: Failed to exec reset-password script
13 verbose stack Error: peertube@1.0.0-beta.1 reset-password: `node ./dist/scripts/reset-password.js "-u" "root"`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/opt/node_n/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/opt/node_n/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid peertube@1.0.0-beta.1
15 verbose cwd /var/www/peertube
16 verbose Linux 4.9.0-0.bpo.5-amd64
17 verbose argv "/opt/node_n/bin/node" "/opt/node_n/bin/npm" "run" "reset-password" "--" "-u" "root"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error peertube@1.0.0-beta.1 reset-password: `node ./dist/scripts/reset-password.js "-u" "root"`
22 error Exit status 255
23 error Failed at the peertube@1.0.0-beta.1 reset-password script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]
```

For now, I've commented out the line to finish the install. 

And then when I do the command line manually it works. 

Might it be the sleep 5 which is too short ?

**Comment by anmol26s** [comment]
Can you try the package again? Its working for me.
Did you get the warning after you removed the reset password line ?
Warning: User unknown.
Warning: npm ERR! code ELIFECYCLE
Warning: npm ERR! errno 255

**Comment by arthurlutz** [comment]
Commenting and then launching the command worked. I then had to reinstall peertube for some other reason and tried installing it with sleep 15 which worked.

**Comment by anmol26s** [comment]
@rigelk would could help in this. I tried installing the app few times and it worked. Maybe its server configuration which matter.

**Comment by rigelk** [comment]
well the `sleep 5` is a very unorthodox way to wait for the service to be alive, and we could surely increase it a bit, but the thing we should do is actually provide a proper way to watch for the event of peertube starting (`grep` until we see "server started" in the log file of peertube, for instance).

**Comment by anmol26s** [comment]
For now sleep has been increased to 15. So closing it for now.

**Comment by Rafi594** [comment]
Same problem
```

296019 DEBUG > peertube@1.0.0-beta.8 reset-password /var/www/peertube
296020 DEBUG > node ./dist/scripts/reset-password.js "-u" "root"
296020 DEBUG 
300785 WARNING User unknown.
300813 WARNING npm ERR! code ELIFECYCLE
300813 WARNING npm ERR! errno 255
300814 WARNING npm ERR! peertube@1.0.0-beta.8 reset-password: `node ./dist/scripts/reset-password.js "-u" "root"`
300814 WARNING npm ERR! Exit status 255
300814 WARNING npm ERR!
300815 WARNING npm ERR! Failed at the peertube@1.0.0-beta.8 reset-password script.
300815 WARNING npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
300947 WARNING 
300948 WARNING npm ERR! A complete log of this run can be found in:
300948 WARNING npm ERR!     /root/.npm/_logs/2018-06-22T10_53_51_171Z-debug.log
300955 DEBUG + ynh_exit_properly
300956 DEBUG + local exit_code=255
300956 WARNING !!
300956 WARNING   peertube's script has encountered an error. Its execution was cancelled.
```

**Comment by anmol26s** [comment]
Maybe @rigelk tell can what should be grep in journalctl -feu peertube to know that the service running?
