### ISSUE TITLE
Installation fails on 3.4.2.4 (gyp crash)

### ISSUE THREAD

**Issue by QGuLL** [YunoHost-Apps/peertube_ynh#80]
Hi,
I've a pretty old yunohost that I've upgraded for years. I'm in 3.4.2.4 and am trying to install peertube, but the installation script is failing.
I've followed the howto and added a domain only for this app.

Here is the log : https://paste.yunohost.org/raw/uhinobupon

It seems to be a problem with gyp :
>2019-02-22 10:02:27,301: WARNING - error /var/www/peertube/node_modules/rdf-canonize: Command failed.
2019-02-22 10:02:27,303: WARNING - Exit code: 1
2019-02-22 10:02:27,304: WARNING - Command: node-gyp rebuild
2019-02-22 10:02:27,305: WARNING - Arguments:
2019-02-22 10:02:27,307: WARNING - Directory: /var/www/peertube/node_modules/rdf-canonize
2019-02-22 10:02:27,308: WARNING - Output:
2019-02-22 10:02:27,310: WARNING - /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
2019-02-22 10:02:27,311: WARNING - sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
2019-02-22 10:02:27,313: WARNING - /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
2019-02-22 10:02:27,314: WARNING - gyp info it worked if it ends with ok
2019-02-22 10:02:27,315: WARNING - gyp info using node-gyp@3.8.0
2019-02-22 10:02:27,317: WARNING - gyp info using node@8.15.0 | linux | x64
2019-02-22 10:02:27,318: WARNING - gyp info spawn /usr/bin/python2
2019-02-22 10:02:27,319: WARNING - gyp info spawn args [ '/opt/node_n/n/versions/node/8.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2019-02-22 10:02:27,321: WARNING - gyp info spawn args   'binding.gyp',
2019-02-22 10:02:27,322: WARNING - gyp info spawn args   '-f',
2019-02-22 10:02:27,323: WARNING - gyp info spawn args   'make',
2019-02-22 10:02:27,324: WARNING - gyp info spawn args   '-I',
2019-02-22 10:02:27,326: WARNING - gyp info spawn args   '/var/www/peertube/node_modules/rdf-canonize/build/config.gypi',
2019-02-22 10:02:27,327: WARNING - gyp info spawn args   '-I',
2019-02-22 10:02:27,328: WARNING - gyp info spawn args   '/opt/node_n/n/versions/node/8.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2019-02-22 10:02:27,330: WARNING - gyp info spawn args   '-I',
2019-02-22 10:02:27,331: WARNING - gyp info spawn args   '/root/.node-gyp/8.15.0/include/node/common.gypi',
2019-02-22 10:02:27,333: WARNING - gyp info spawn args   '-Dlibrary=shared_library',
2019-02-22 10:02:27,334: WARNING - gyp info spawn args   '-Dvisibility=default',
2019-02-22 10:02:27,335: WARNING - gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.15.0',
2019-02-22 10:02:27,337: WARNING - gyp info spawn args   '-Dnode_gyp_dir=/opt/node_n/n/versions/node/8.15.0/lib/node_modules/npm/node_modules/node-gyp',
2019-02-22 10:02:27,338: WARNING - gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.15.0/<(target_arch)/node.lib',
2019-02-22 10:02:27,339: WARNING - gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/node_modules/rdf-canonize',
2019-02-22 10:02:27,341: WARNING - gyp info spawn args   '-Dnode_engine=v8',
2019-02-22 10:02:27,342: WARNING - gyp info spawn args   '--depth=.',
2019-02-22 10:02:27,344: WARNING - gyp info spawn args   '--no-parallel',
2019-02-22 10:02:27,345: WARNING - gyp info spawn args   '--generator-output',
2019-02-22 10:02:27,346: WARNING - gyp info spawn args   'build',
2019-02-22 10:02:27,348: WARNING - gyp info spawn args   '-Goutput_dir=.' ]
2019-02-22 10:02:27,351: WARNING - /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
2019-02-22 10:02:27,352: WARNING - /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
2019-02-22 10:02:27,354: WARNING - gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
2019-02-22 10:02:27,355: WARNING - gyp ERR! configure error
2019-02-22 10:02:27,356: WARNING - gyp ERR! stack Error: `gyp` failed with exit code: 1
2019-02-22 10:02:27,358: WARNING - gyp ERR! stack     at ChildProcess.onCpExit (/opt/node_n/n/versions/node/8.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
2019-02-22 10:02:27,359: WARNING - gyp ERR! stack     at emitTwo (events.js:126:13)
2019-02-22 10:02:27,361: WARNING - gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
2019-02-22 10:02:27,362: WARNING - gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-02-22 10:02:27,363: WARNING - gyp ERR! System Linux 4.9.0-8-amd64
2019-02-22 10:02:27,364: WARNING - gyp ERR! command "/opt/node_n/n/versions/node/8.15.0/bin/node" "/opt/node_n/n/versions/node/8.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-02-22 10:02:27,365: WARNING - gyp ERR! cwd /var/www/peertube/node_modules/rdf-canonize
2019-02-22 10:02:27,365: WARNING - gyp ERR! node -v v8.15.0
2019-02-22 10:02:27,366: WARNING - gyp ERR! node-gyp -v v3.8.0
2019-02-22 10:02:27,367: WARNING - gyp ERR! not ok

**Comment by QGuLL** [comment]
I've manage to install it by doing this : 
* Migrate my old psql db from 9.1 to 9.6 (haven't seen that the 9.1 was still running, it might have failed something when i've upgrade from wheezy to jessie years ago)
* follow theses steps : https://github.com/Chocobozzz/PeerTube/issues/830#issuecomment-425942717

**Comment by yalh76** [comment]
Peertube_ynh has been updated, you can try to upgrade using:
`yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh`

**Comment by QGuLL** [comment]
Still the same error.
>Attention : gyp info spawn /usr/bin/python2
Attention : gyp info spawn args [ '/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
Attention : gyp info spawn args   'binding.gyp',
Attention : gyp info spawn args   '-f',
Attention : gyp info spawn args   'make',
Attention : gyp info spawn args   '-I',
Attention : gyp info spawn args   '/var/www/peertube/node_modules/rdf-canonize/build/config.gypi',
Attention : gyp info spawn args   '-I',
Attention : gyp info spawn args   '/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
Attention : gyp info spawn args   '-I',
Attention : gyp info spawn args   '/root/.node-gyp/8.16.0/include/node/common.gypi',
Attention : gyp info spawn args   '-Dlibrary=shared_library',
Attention : gyp info spawn args   '-Dvisibility=default',
Attention : gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.16.0',
Attention : gyp info spawn args   '-Dnode_gyp_dir=/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp',
Attention : gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.16.0/<(target_arch)/node.lib',
Attention : gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/node_modules/rdf-canonize',
Attention : gyp info spawn args   '-Dnode_engine=v8',
Attention : gyp info spawn args   '--depth=.',
Attention : gyp info spawn args   '--no-parallel',
Attention : gyp info spawn args   '--generator-output',
Attention : gyp info spawn args   'build',
Attention : gyp info spawn args   '-Goutput_dir=.' ]
Attention : /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
Attention : /bin/sh: BASH_XTRACEFD : 7 : valeur non valable pour un descripteur de fichier de trace
Attention : gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
Attention : gyp ERR! configure error
Attention : gyp ERR! stack Error: `gyp` failed with exit code: 1
Attention : gyp ERR! stack     at ChildProcess.onCpExit (/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
Attention : gyp ERR! stack     at emitTwo (events.js:126:13)
Attention : gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
Attention : gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Attention : gyp ERR! System Linux 4.9.0-8-amd64
Attention : gyp ERR! command "/opt/node_n/n/versions/node/8.16.0/bin/node" "/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
Attention : gyp ERR! cwd /var/www/peertube/node_modules/rdf-canonize
Attention : gyp ERR! node -v v8.16.0
Attention : gyp ERR! node-gyp -v v3.8.0
Attention : gyp ERR! not ok
Attention : !!
Attention :   peertube's script has encountered an error. Its execution was cancelled.
Attention : !!

**Comment by yalh76** [comment]
Ok then, can you launch the upgrade using `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh --debug` and give the link to the logs to check what happens

**Comment by QGuLL** [comment]
I can no longer upgrade because it uninstalls it when the script fails, and now it's uninstalled.
Should I try something like `yunohost app install peertube -u https://github.com/YunoHost-Apps/peertube_ynh --debug` ?

**Comment by yalh76** [comment]
To install it you can execute :  `yunohost app install peertube https://github.com/YunoHost-Apps/peertube_ynh --debug`

**Comment by raphgilles** [comment]
Hello,

I have exactly the same error. That was fixed with an old ovh-fix that don't exist anymore.
So I search a solution.

> 2019-05-31 13:02:18,142: DEBUG - yarn install v1.16.0
2019-05-31 13:02:18,343: DEBUG - [1/5] Validating package.json...
2019-05-31 13:02:18,343: DEBUG - [2/5] Resolving packages...
2019-05-31 13:02:18,643: WARNING - warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
2019-05-31 13:02:19,044: DEBUG - [3/5] Fetching packages...
2019-05-31 13:02:19,746: DEBUG - info fsevents@1.2.4: The platform "linux" is incompatible with this module.
2019-05-31 13:02:19,746: DEBUG - info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
2019-05-31 13:02:19,746: DEBUG - [4/5] Linking dependencies...
2019-05-31 13:02:24,554: DEBUG - [5/5] Building fresh packages...
2019-05-31 13:02:25,356: DEBUG - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2019-05-31 13:02:25,356: WARNING - error /var/www/peertube/node_modules/rdf-canonize: Command failed.
2019-05-31 13:02:25,356: WARNING - Exit code: 1
2019-05-31 13:02:25,356: WARNING - Command: node-gyp rebuild
2019-05-31 13:02:25,356: WARNING - Arguments:
2019-05-31 13:02:25,356: WARNING - Directory: /var/www/peertube/node_modules/rdf-canonize
2019-05-31 13:02:25,357: WARNING - Output:
2019-05-31 13:02:25,357: WARNING - /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2019-05-31 13:02:25,357: WARNING - sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2019-05-31 13:02:25,357: WARNING - /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2019-05-31 13:02:25,357: WARNING - gyp info it worked if it ends with ok
2019-05-31 13:02:25,357: WARNING - gyp info using node-gyp@3.8.0
2019-05-31 13:02:25,358: WARNING - gyp info using node@8.16.0 | linux | x64
2019-05-31 13:02:25,358: WARNING - gyp info spawn /usr/bin/python2
2019-05-31 13:02:25,358: WARNING - gyp info spawn args [ '/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2019-05-31 13:02:25,358: WARNING - gyp info spawn args   'binding.gyp',
2019-05-31 13:02:25,358: WARNING - gyp info spawn args   '-f',
2019-05-31 13:02:25,358: WARNING - gyp info spawn args   'make',
2019-05-31 13:02:25,358: WARNING - gyp info spawn args   '-I',
2019-05-31 13:02:25,358: WARNING - gyp info spawn args   '/var/www/peertube/node_modules/rdf-canonize/build/config.gypi',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '-I',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '-I',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '/root/.node-gyp/8.16.0/include/node/common.gypi',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '-Dlibrary=shared_library',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '-Dvisibility=default',
2019-05-31 13:02:25,359: WARNING - gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.16.0',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '-Dnode_gyp_dir=/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.16.0/<(target_arch)/node.lib',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '-Dmodule_root_dir=/var/www/peertube/node_modules/rdf-canonize',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '-Dnode_engine=v8',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '--depth=.',
2019-05-31 13:02:25,360: WARNING - gyp info spawn args   '--no-parallel',
2019-05-31 13:02:25,361: WARNING - gyp info spawn args   '--generator-output',
2019-05-31 13:02:25,361: WARNING - gyp info spawn args   'build',
2019-05-31 13:02:25,361: WARNING - gyp info spawn args   '-Goutput_dir=.' ]
2019-05-31 13:02:25,361: WARNING - /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2019-05-31 13:02:25,361: WARNING - /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
2019-05-31 13:02:25,361: WARNING - gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
2019-05-31 13:02:25,361: WARNING - gyp ERR! configure error
2019-05-31 13:02:25,362: WARNING - gyp ERR! stack Error: `gyp` failed with exit code: 1
2019-05-31 13:02:25,362: WARNING - gyp ERR! stack     at ChildProcess.onCpExit (/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
2019-05-31 13:02:25,362: WARNING - gyp ERR! stack     at emitTwo (events.js:126:13)
2019-05-31 13:02:25,362: WARNING - gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
2019-05-31 13:02:25,362: WARNING - gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
2019-05-31 13:02:25,362: WARNING - gyp ERR! System Linux 4.9.179-xxxx-std-ipv6-64
2019-05-31 13:02:25,362: WARNING - gyp ERR! command "/opt/node_n/n/versions/node/8.16.0/bin/node" "/opt/node_n/n/versions/node/8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-05-31 13:02:25,362: WARNING - gyp ERR! cwd /var/www/peertube/node_modules/rdf-canonize
2019-05-31 13:02:25,363: WARNING - gyp ERR! node -v v8.16.0
2019-05-31 13:02:25,363: WARNING - gyp ERR! node-gyp -v v3.8.0
2019-05-31 13:02:25,363: WARNING - gyp ERR! not ok

**Comment by yalh76** [comment]
@anmol26s do you remember what you made in the ovh-fix ?
Just removing install steps to let user install peertube manually ?

**Comment by raphgilles** [comment]
Here are the steps : https://github.com/Chocobozzz/PeerTube/issues/830#issuecomment-425942717

**Comment by yalh76** [comment]
Well there is PeerTube 1.3.0 in the testing branch.

Can someone test installing it on an OVH hosting and let us know if it's working or not.

If not, I will recreate the ovh-fix branch

**Comment by raphgilles** [comment]
I tried. With the same error.

**Comment by yalh76** [comment]
ovh_fix back online, you can apply https://github.com/Chocobozzz/PeerTube/issues/830#issuecomment-425942717

**Comment by raphgilles** [comment]
Perfect ! Thank you !

Now, my instance is not federated. But I don't think that it's a YunoHost error.

**Comment by gnouts** [comment]
Hi, same issue here. I'm hosted on kimsufi, using the ovh_fix did not help.
Here is my log : https://paste.yunohost.org/raw/bulejukejo
(restore is working fine, though :slightly_smiling_face: )
I ran `apt upgrade` just before.

```
nouts@alttube:~$ uname -a
Linux alttube 4.9.168-xxxx-std-ipv6-64 #665790 SMP Mon Apr 8 08:31:26 UTC 2019 x86_64 GNU/Linux
nouts@alttube:~$ node -v
v8.16.0
nouts@alttube:~$ yarn -v
1.16.0
nouts@alttube:~$ npm -v
6.4.1
```

**Comment by yalh76** [comment]
I just applied updated upgrade script in ovh_fix branch.
You just have to:
1. upgrade peertube using `yunohost app upgrade peertube -u https://github.com/YunoHost-Apps/peertube_ynh/tree/ovh_fix`
1. run yarn install with `cd /var/www/peertube && yarn install --production --pure-lockfile`
1. Restart peertube using `service peertube restart`

**Comment by raphgilles** [comment]
Oh ! And it's not the subject of this issue, but we must to comment the line 59 of the nginf .conf file : 
# more_set_headers "X-Frame-Options : SAMEORIGIN";

If it's not commented, we can't show iframes on other domains.

**Comment by yalh76** [comment]
> more_set_headers "X-Frame-Options : SAMEORIGIN";

yes, mixing issues is very very very very bad thing to do :p

**Comment by gnouts** [comment]
@yalh76 thanks, upgrade worked ;)

**Comment by yalh76** [comment]
> 
> 
> Edit : I made a PR to update the readme with proper command line examples #96

Thanks :) it helps a lot
