### ISSUE TITLE
Upgrade failed because change of database name ? 

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/peertube_ynh#83]
Trying to upgrade I got a unavailable site, and peertube using up a lot of CPU. The service as far as systemctl was concerned was not failing. Checking out syslog : 

```
Mar 19 06:29:50 yunohost peertube[29207]: [videos.festivalparminous.org:443] 2019-03-19 06:29:50.587 #033[31merror#033[39m: Cannot start application. {
Mar 19 06:29:50 yunohost peertube[29207]:   "meta": {
Mar 19 06:29:50 yunohost peertube[29207]:     "err": {
Mar 19 06:29:50 yunohost peertube[29207]:       "stack": "SequelizeConnectionError: database \"peertube_peertube\" does not exist\n    at connection.connect.err (/var/www/peertube/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:128:24)\n    at Connection.connectingErrorHandler (/var/www/peertube/node_modules/pg/lib/client.js:140:14)\n    at emitOne (events.js:116:13)\n    at Connection.emit (events.js:211:7)\n    at Socket.<anonymous> (/var/www/peertube/node_modules/pg/lib/connection.js:124:12)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
Mar 19 06:29:50 yunohost peertube[29207]:       "message": "database \"peertube_peertube\" does not exist",
Mar 19 06:29:50 yunohost peertube[29207]:       "name": "SequelizeConnectionError",
Mar 19 06:29:50 yunohost peertube[29207]:       "parent": {
Mar 19 06:29:50 yunohost peertube[29207]:         "stack": "error: database \"peertube_peertube\" does not exist\n    at Connection.parseE (/var/www/peertube/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
Mar 19 06:29:50 yunohost peertube[29207]:         "message": "database \"peertube_peertube\" does not exist",
Mar 19 06:29:50 yunohost peertube[29207]:         "name": "error",
Mar 19 06:29:50 yunohost peertube[29207]:         "length": 102,
Mar 19 06:29:50 yunohost peertube[29207]:         "severity": "FATAL",
Mar 19 06:29:50 yunohost peertube[29207]:         "code": "3D000",
Mar 19 06:29:50 yunohost peertube[29207]:         "file": "postinit.c",
Mar 19 06:29:50 yunohost peertube[29207]:         "line": "841",
Mar 19 06:29:50 yunohost peertube[29207]:         "routine": "InitPostgres"
Mar 19 06:29:50 yunohost peertube[29207]:       },
Mar 19 06:29:50 yunohost peertube[29207]:       "original": {
Mar 19 06:29:50 yunohost peertube[29207]:         "stack": "error: database \"peertube_peertube\" does not exist\n    at Connection.parseE (/var/www/peertube/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/var/www/peertube/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/var/www/peertube/node_modules/pg/lib/connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)",
Mar 19 06:29:50 yunohost peertube[29207]:         "message": "database \"peertube_peertube\" does not exist",
Mar 19 06:29:50 yunohost peertube[29207]:         "name": "error",
Mar 19 06:29:50 yunohost peertube[29207]:         "length": 102,
Mar 19 06:29:50 yunohost peertube[29207]:         "severity": "FATAL",
Mar 19 06:29:50 yunohost peertube[29207]:         "code": "3D000",
Mar 19 06:29:50 yunohost peertube[29207]:         "file": "postinit.c",
Mar 19 06:29:50 yunohost peertube[29207]:         "line": "841",
Mar 19 06:29:50 yunohost peertube[29207]:         "routine": "InitPostgres"
Mar 19 06:29:50 yunohost peertube[29207]:       }
Mar 19 06:29:50 yunohost peertube[29207]:     }
Mar 19 06:29:50 yunohost peertube[29207]:   },
```
Looking at `psql -l` (after doing `su postgres`) I see a `peertube_prod` database. 

Issuing the following command solved the problem : 

```
sudo -s
su postgres
psql 
postgres=# ALTER DATABASE peertube_prod RENAME to peertube_peertube
ctrl-D
systemctl restart peertube
```

**Comment by yalh76** [comment]
Hi @arthurlutz 

Another way to solve that would be to execute: 
`yunohost app setting peertube psql_db -v peertube_prod`

and then execute the upgrade
